USB_VID = 0x239A
USB_PID = 0x8110

USB_PRODUCT = "Feather ESP32-S2 TFT"
USB_MANUFACTURER = "Adafruit"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_ESP32_CAMERA = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_TOUCHIO_USE_NATIVE = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_PARALLELDISPLAY = 0
CIRCUITPY_RGBMATRIX = 0
OPTIMIZATION_FLAGS = -Os
