# SPDX-FileCopyrightText: Copyright (c) 2019 Anthony Sottile
#
# SPDX-License-Identifier: MIT

name: pre-commit

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install deps
      run: |
        sudo apt-get install -y gettext uncrustify
        pip3 install black polib pyyaml
    - name: Populate selected submodules
      run: git submodule update --init extmod/ulab
    - name: Set PY
      run: echo >>$GITHUB_ENV PY="$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v3.0.0
    - name: Make patch
      if: failure()
      run: git diff > ~/pre-commit.patch
    - name: Upload patch
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: patch
        path: ~/pre-commit.patch
